Repository pondpilot/pondpilot, pull requests merged in 2025-03, with the labels that each got.

#5 Set up regular Cloudflare Pages deploymenent
  .github/workflows/deploy-pages.yml
  README.md
  package.json
  yarn.lock
Labels: documentation, infra

#13 Add docker deployement
  .github/workflows/deploy-pages.yml
  .github/workflows/docker-build.yml
  README.md
  docker/Dockerfile
  justfile
Labels: infra

#30 Update Vite configuration to fix PWA issue
  public/168.png
  public/192.png
  public/512.png
  public/icon168.png
  public/icon192.png
  public/icon512.png
  vite.config.mjs
Labels: bug, infra

#9 [Feature]: Settings page component and minor improvements
  src/app.tsx
  src/assets/dark-logo.svg
  src/assets/logo.svg
  src/components/layout/components/header.tsx
  src/components/settings-modal/settings-modal.tsx
  src/components/settings-modal/utils.ts
  src/components/spotlight/spotlight.tsx
  src/components/table/components/table-cell.tsx
  src/components/table/components/thead-cell.tsx
  src/components/table/hooks/useTableColumns.tsx
  src/components/table/table.tsx
  src/consts/idb.ts
  src/features/app-context/app-context.tsx
  src/features/app-context/app-session-worker.ts
  src/features/app-context/db-worker.ts
  src/features/app-context/models.ts
  src/features/app-context/utils.ts
  src/features/data-viewer/components/start-guide.tsx
  src/features/data-viewer/data-viewer.tsx
  src/features/data-viewer/hooks/useColumnSummary.tsx
  src/features/data-viewer/hooks/useTableExport.tsx
  src/features/data-viewer/hooks/useTablePaginationSort.tsx
  src/features/db-explorer/db-explorer.tsx
  src/features/editor/auto-complete.tsx
  src/features/error-fallback/views/app-error-fallback.tsx
  src/features/error-fallback/views/data-view-error-fallback.tsx
  src/features/query-editor/query-editor.tsx
  src/features/query-explorer/query-explorer.tsx
  src/features/tabs-pane/tabs-pane.tsx
  src/features/view-explorer/view-explorer.tsx
  src/hooks/useUploadFilesHandlers.tsx
  src/index.css
  src/main.tsx
  src/models/common.ts
  src/models/table.ts
  src/pages/index.ts
  src/pages/main-page/components/index.ts
  src/pages/main-page/components/navbar.tsx
  src/pages/main-page/index.ts
  src/pages/main-page/main-page.tsx
  src/pages/settings-page/components/theme-switcher/index.ts
  src/pages/settings-page/components/theme-switcher/theme-switcher.tsx
  src/pages/settings-page/index.ts
  src/pages/settings-page/settings-page.tsx
  src/router/router.tsx
  src/store/app-store.tsx
  src/store/pagination-store.tsx
  src/theme/theme.ts
  src/utils.ts
  src/utils/helpers.ts
  tsconfig.json
  vite.config.mjs
Labels: enhancement

#45 Add Playwright testing framework and configure CI workflow
  .eslintignore
  .github/workflows/pw-tests.yml
  .gitignore
  package.json
  playwright.config.ts
  src/app.tsx
  src/components/table/hooks/useTableColumns.tsx
  src/features/app-status/app-status.tsx
  src/features/app-status/index.ts
  src/features/query-editor/components/run-query-button/run-query-button.tsx
  src/features/query-explorer/query-explorer.tsx
  tests/integration/query.spec.ts
  tsconfig.json
  vite.config.mjs
  yarn.lock
Labels: infra

#51 Re-org & harden security of testing and deployment workflows
  .github/workflows/build-and-test.yml
  .github/workflows/deploy-pages.yml
  .github/workflows/docker-build.yml
  .github/workflows/pr.yml
  .github/workflows/pw-tests.yml
  docker/Dockerfile
  justfile
  playwright.config.ts
Labels: infra

#54 [UX]: Update PWA Icon
  public/168.png
  public/192.png
  public/512.png
Labels: ux

#53 Add missing release CI workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/build-and-test.yml
  .github/workflows/pr-maintenance.yml
  .github/workflows/pr-post-test.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: infra

#36 Fix query disappearing when switching tabs
  .eslintignore
  .stylelintignore
  src/components/layout/components/header.tsx
  src/components/sources-list-view/sources-list-view.tsx
  src/components/spotlight/spotlight.tsx
  src/features/app-context/app-context.tsx
  src/features/app-context/app-session-worker.ts
  src/features/app-context/utils.ts
  src/features/db-explorer/db-explorer.tsx
  src/features/query-editor/components/run-query-button/run-query-button.tsx
  src/features/query-editor/query-editor.tsx
  src/features/query-explorer/query-explorer.tsx
  src/features/tabs-pane/tabs-pane.tsx
  src/features/view-explorer/view-explorer.tsx
  tests/integration/query.spec.ts
Labels: bug

#11 [Bug]: Fix autocomplete icons color
  .eslintrc.cjs
  public/assets/database-dark.svg
  public/assets/database.svg
  public/assets/pwa-icons/168.png
  public/assets/pwa-icons/192.png
  public/assets/pwa-icons/512.png
  public/assets/schema-dark.svg
  public/assets/schema.svg
  public/assets/table-dark.svg
  public/assets/table.svg
  public/database.svg
  public/schema.svg
  public/table.svg
  src/components/layout/components/header.tsx
  src/components/table/utils.tsx
  src/favicon.svg
  src/features/app-context/app-context.tsx
  src/features/app-context/db-worker.ts
  src/features/app-context/utils.ts
  src/features/db-explorer/db-explorer.tsx
  src/features/error-fallback/views/app-error-fallback.tsx
  src/features/view-explorer/view-explorer.tsx
  src/hooks/useUploadFilesHandlers.tsx
  src/index.css
  src/pages/main-page/components/navbar.tsx
  src/utils/duckdb/describeColumns.ts
  src/utils/duckdb/index.ts
  vite.config.mjs
Labels: ux

#50 [UX]: Fix ui issues
  .eslintrc.cjs
  src/components/table/components/table-cell.tsx
  src/components/table/components/thead-cell.tsx
  src/components/table/table.tsx
  src/features/app-context/app-session-worker.ts
  src/features/data-viewer/data-viewer.tsx
  src/features/editor/sql-editor.tsx
  src/utils/editor/highlight-plugin.ts
  src/utils/editor/statement-parser.ts
  src/utils/helpers.ts
  tests/integration/consts.ts
  tests/integration/query.spec.ts
Labels: bug, ux

#67 [UX]: Update issue link in SpotlightMenu component
  src/components/spotlight/spotlight.tsx
Labels: ux

#68 Truncate long text in Spotlight
  src/components/sources-list-view/sources-list-view.tsx
  src/components/spotlight/spotlight.tsx
  src/features/app-context/app-session-worker.ts
  src/features/editor/sql-editor.tsx
  src/features/query-editor/query-editor.tsx
  tests/integration/baseTest.tsx
  tests/integration/query/consts.ts
  tests/integration/query/query.spec.ts
  tests/integration/spotlight/spotlight.spec.ts
Labels: bug, ux

#87 [UX] Do not show pagination when only one data page exist
  .eslintrc.cjs
  .github/workflows/build-and-test.yml
  justfile
  package.json
  src/components/browser-not-supported/browser-not-supported.tsx
  src/components/layout/components/header.tsx
  src/components/sources-list-view/sources-list-view.tsx
  src/components/spotlight/spotlight.tsx
  src/components/table/components/table-cell.tsx
  src/components/table/components/thead-cell.tsx
  src/components/table/hooks/useTableColumns.tsx
  src/components/table/table.tsx
  src/features/data-viewer/components/pagination-control.tsx
  src/features/data-viewer/data-viewer.tsx
  src/features/query-editor/components/run-query-button/run-query-button.tsx
  src/features/query-editor/query-editor.tsx
  src/features/query-explorer/query-explorer.tsx
  src/features/tabs-pane/tabs-pane.tsx
  src/utils/test-id.ts
  tests/integration/data-viewer/pagination.spec.ts
  tests/integration/fixtures/data-view.ts
  tests/integration/fixtures/explorer.ts
  tests/integration/fixtures/page.ts
  tests/integration/fixtures/query-editor.ts
  tests/integration/fixtures/spotlight.ts
  tests/integration/fixtures/tab.ts
  tests/integration/query/consts.ts
  tests/integration/query/query.spec.ts
  tests/integration/spotlight/spotlight.spec.ts
  yarn.lock
Labels: enhancement, ux

#89 Use a workaround to consistently get workflow run conclusion
  .github/workflows/deploy-pages.yml
  .github/workflows/pr-maintenance.yml
  .github/workflows/pr-post-test.yml
Labels: infra, skip-changelog

#90 [UX]: improveme unsupported browser layout and settings pages
  .gitattributes
  playwright.config.ts
  src/components/browser-not-supported/assets/bsod.svg
  src/components/browser-not-supported/assets/matrix.svg
  src/components/browser-not-supported/assets/wat.png
  src/components/browser-not-supported/assets/wat.svg
  src/components/browser-not-supported/browser-not-supported.tsx
  src/components/layout/components/header.tsx
  src/components/spotlight/components/spotlight-breadcrumbs/spotlight-breadcrumbs.tsx
  src/components/spotlight/models.ts
  src/components/spotlight/spotlight.tsx
  src/components/spotlight/utlis.tsx
  src/pages/main-page/components/navbar.tsx
  src/pages/settings-page/settings-page.tsx
  src/theme/theme.ts
  tests/integration/fixtures/query-editor.ts
  tests/integration/fixtures/settings.ts
  tests/integration/fixtures/spotlight.ts
  tests/integration/settings/settings.spec.ts
Labels: bug, ux
