Repository pondpilot/pondpilot, pull requests merged in 2025-04, with the labels that each got.

#100 Add-files testing framework
  .gitignore
  src/pages/main-page/components/navbar.tsx
  tests/integration/add-files/add-files.spec.ts
  tests/integration/fixtures/explorer.ts
  tests/integration/fixtures/file-picker.ts
  tests/integration/fixtures/page.ts
  tests/integration/fixtures/spotlight.ts
  tests/integration/fixtures/storage.ts
  tests/integration/fixtures/test-tmp.ts
  tests/utils.ts
Labels: infra, skip-changelog

#108 [Bug]: Use valid identifiers for colnames in script table sorting
  src/utils/data-adapter.ts
Labels: bug, skip-changelog

#107 [Feature]: Add automatic retry when file source was moved or changed
  src/controllers/data-source/data-view-source.ts
  src/controllers/db/data-source.ts
  src/controllers/file-system/file-system-controller.ts
  src/features/tab-view/components/script-tab-view.tsx
  src/features/tab-view/hooks/use-data-adapter.ts
  src/store/app-store.tsx
  src/store/restore.ts
Labels: enhancement

#106 [BUG]: Fix calculate total
  src/features/tab-view/components/data-view.tsx
  src/features/tab-view/hooks/use-column-summary.tsx
  src/utils/db.ts
  src/utils/helpers.ts
Labels: bug, skip-changelog

#112 [Bug]: Fix rows duplication in dev mode & connection leaks
  src/controllers/file-system/file-system-controller.ts
  src/features/duckdb-context/duckdb-pooled-streaming-reader.ts
  src/features/tab-view/components/data-view-info-pane/data-view-info-pane.tsx
  src/features/tab-view/hooks/use-data-adapter.ts
  tests/integration/fixtures/page.ts
Labels: bug, skip-changelog

#114 [Bug]: Auto-close outdated tabs when restoring state on page reload
  src/store/restore.ts
Labels: bug, skip-changelog

#115 [BUG]: fix copy to clipboard
  .eslintrc.cjs
  src/features/tab-view/components/data-view.tsx
  src/features/tab-view/hooks/use-table-export.tsx
Labels: bug, skip-changelog

#110 [Feature]: Use tab name for exported file
  src/features/tab-view/components/data-view-info-pane/data-view-info-pane.tsx
  src/features/tab-view/components/file-data-source-tab-view.tsx
  src/features/tab-view/components/script-tab-view.tsx
  src/features/tab-view/hooks/use-table-export.tsx
Labels: enhancement, skip-changelog

#99 [Feature]: Show onboarding video for first-time users
  CONTRIBUTING.md
  index.html
  package.json
  public/favicon.svg
  src/app.tsx
  src/components/error-fallback/views/app-error-fallback.tsx
  src/components/spotlight/spotlight.tsx
  src/features/init-modals/index.tsx
  src/features/init-modals/init-modals.tsx
  src/features/onboarding-modal-content/index.ts
  src/features/onboarding-modal-content/onboarding-modal.tsx
  src/features/script-editor/components/components/run-query-button/run-query-button.tsx
  src/features/start-guide/index.ts
  src/features/start-guide/start-guide.tsx
  src/models/app-urls.ts
  src/models/local-storage.ts
  src/pages/main-page/components/navbar.tsx
  src/pages/main-page/main-page.tsx
  src/theme/theme.ts
  src/utils/compare-versions.ts
  tests/integration/fixtures/page.ts
  tests/integration/onboarding/onboarding.spec.ts
  tests/integration/webkit/onboarding.spec.ts
  yarn.lock
Labels: documentation, enhancement

#109 [Bug]: Handle strictly reserved `temp` and `system` in ATTACH <database> statement
  .eslintrc.cjs
  .github/workflows/build-and-test.yml
  CONTRIBUTING.md
  justfile
  src/components/explorer-tree/components/tree-node.tsx
  src/components/explorer-tree/model.ts
  src/components/explorer-tree/utils/context-menu.ts
  src/components/explorer-tree/utils/node-test-id.ts
  src/pages/main-page/components/navbar.tsx
  src/utils/data-source.ts
  src/utils/duckdb/identifier.ts
  tests/integration/add-files/add-files.spec.ts
  tests/integration/file-import-export/add-files.spec.ts
  tests/integration/file-import-export/export.spec.ts
  tests/integration/fixtures/data-view.ts
  tests/integration/fixtures/db-explorer.ts
  tests/integration/fixtures/file-picker.ts
  tests/integration/fixtures/file-system-explorer.ts
  tests/integration/fixtures/page.ts
  tests/integration/fixtures/script-explorer.ts
  tests/integration/fixtures/storage.ts
  tests/integration/fixtures/utils/explorer-tree.ts
  tests/integration/script/script-explorer.spec.ts
  vite.config.mjs
Labels: bug

#116 Optimize XLSX sheets names extraction
  package.json
  src/utils/xlsx.ts
  tests/integration/file-import-export/add-files.spec.ts
  tests/integration/fixtures/file-system-explorer.ts
  yarn.lock
Labels: bug, skip-changelog

#122 [UX]: Add a close button on the settings page, improve query editor focus and minor UI tweaks
  src/components/spotlight/spotlight.tsx
  src/features/script-editor/script-editor.tsx
  src/pages/settings-page/settings-page.tsx
  src/theme/theme.ts
  tests/integration/script/script-explorer.spec.ts
  tests/integration/settings/settings.spec.ts
Labels: enhancement, ux

#125 [Perf]: Optimize page loads & tests
  .github/workflows/build-and-test.yml
  .gitignore
  index.html
  justfile
  package.json
  playwright.config.ts
  src/features/tab-view/hooks/use-data-adapter.ts
  src/globals.d.ts
  src/router/router.tsx
  src/utils/test-id.ts
  tests/integration/error-fallback.spec.ts
  tests/integration/fixtures/README.md
  tests/integration/fixtures/base.ts
  tests/integration/fixtures/page.ts
  tests/integration/onboarding/onboarding.spec.ts
  tests/integration/webkit/404.spec.ts
  tests/integration/webkit/onboarding.spec.ts
  vite.config.mjs
  yarn.lock
Labels: enhancement, infra, skip-changelog
