Repository pondpilot/pondpilot, pull requests merged in 2025-05, with the labels that each got.

#130 [Bug]: Add keyboard shortcut for creating a new script from the Editor
  src/features/editor/sql-editor.tsx
  src/features/script-editor/script-editor.tsx
  src/utils/hotkey/key-matcher.ts
  tests/integration/script/script-explorer.spec.ts
Labels: bug, skip-changelog

#127 [Bug]: Clear ExplorerTree selection on tab change
  src/components/explorer-tree/explorer-tree.tsx
  src/features/db-explorer/db-explorer.tsx
  src/features/file-system-explorer/file-system-explorer.tsx
  src/features/script-explorer/script-explorer.tsx
  tests/integration/db-explorer/db-explorer.spec.ts
  tests/integration/file-explorer/file-explorer.spec.ts
  tests/integration/fixtures/file-system-explorer.ts
  tests/integration/fixtures/global-hotkeys.ts
  tests/integration/fixtures/script-editor.ts
  tests/integration/fixtures/script-explorer.ts
  tests/integration/fixtures/spotlight.ts
  tests/integration/script/script-explorer.spec.ts
  tests/integration/spotlight/spotlight.spec.ts
Labels: bug, skip-changelog

#136 [Bug]: Fix hotkey naming for creating a new script
  src/components/spotlight/spotlight.tsx
  src/features/start-guide/start-guide.tsx
Labels: bug, skip-changelog

#135 [UX]: Add auto-save alert on script save action
  src/features/script-editor/script-editor.tsx
  tests/integration/script/script-editor.spec.ts
Labels: ux

#134 [UX]: Add DesktopOnly component for desktop view restriction
  src/components/browser-not-supported/browser-not-supported.tsx
  src/components/desktop-only/assets/desktop-only.svg
  src/components/desktop-only/desktop-only.tsx
  src/components/desktop-only/index.ts
  src/components/layout/layout.tsx
  src/components/loading-overlay/loading-overlay.tsx
  src/features/app-context/app-context.tsx
  src/features/app-context/hooks/use-init-application.tsx
  src/features/init-modals/init-modals.tsx
  src/features/start-guide/start-guide.tsx
  src/features/tab-view/components/data-view-info-pane/data-view-info-pane.tsx
  src/features/tab-view/components/data-view.tsx
  src/features/tabs-pane/components/tab.tsx
  src/models/browser.ts
  src/router/router.tsx
  src/utils/browser.ts
  src/utils/is-mobile-device.ts
  tailwind.config.js
  tests/integration/desktop-only/desktop-only.spec.ts
  tests/integration/webkit/browser-unsupported.spec.ts
Labels: ux

#132 [UX] Improve how and when loading state is shown and query cancellation behavior
  .github/workflows/docker-build.yml
  README.md
  justfile
  package.json
  src/components/data-loading-overlay/data-loading-overlay.tsx
  src/components/table/components/thead-cell/thead-cell.tsx
  src/features/duckdb-context/duckdb-connection-pool.ts
  src/features/tab-view/components/data-view-info-pane/data-view-info-pane.tsx
  src/features/tab-view/components/data-view.tsx
  src/features/tab-view/components/reset-button.tsx
  src/features/tab-view/hooks/use-data-adapter-queries.ts
  src/features/tab-view/hooks/use-data-adapter.ts
  src/features/tab-view/utils.ts
  src/models/data-adapter.ts
  src/utils/data-adapter.ts
  vite.config.mjs
Labels: bug, enhancement, ux

#128 [Feature, Bug] Add rename support to all data sources and make sure we restore tabs from non-top-level sources
  src/controllers/data-source/persist.ts
  src/controllers/db-explorer.ts
  src/controllers/db/data-source.ts
  src/controllers/file-explorer.ts
  src/controllers/file-system/file-system-controller.ts
  src/features/db-explorer/db-explorer.tsx
  src/features/file-system-explorer/file-system-explorer.tsx
  src/hooks/use-add-local-files-folders.tsx
  src/models/file-system.ts
  src/store/restore.ts
  src/utils/file-system.ts
  src/utils/navigation.ts
  src/utils/xlsx.ts
  tests/integration/db-explorer/db-explorer.spec.ts
  tests/integration/file-explorer/file-explorer.spec.ts
  tests/integration/file-import-export/add-files.spec.ts
  tests/integration/fixtures/db-explorer.ts
  tests/integration/fixtures/file-picker.ts
  tests/integration/fixtures/file-system-explorer.ts
  tests/integration/fixtures/utils/explorer-tree.ts
  tests/integration/models.ts
  tests/utils.ts
Labels: bug, enhancement

#140 Add proper handling of empty XLSX sheets
  src/controllers/file-system/file-system-controller.ts
  src/hooks/use-add-local-files-folders.tsx
  src/store/restore.ts
  tests/integration/file-explorer/file-explorer.spec.ts
  tests/integration/file-import-export/add-files.spec.ts
  tests/integration/fixtures/file-picker.ts
  tests/integration/models.ts
Labels: bug

#154 Improve testing harness & fix flaky tests in CI
  .eslintrc.cjs
  eslint-custom-rules/no-playwright-page-methods.js
  package.json
  playwright.config.ts
  tests/integration/data-viewer/pagination.spec.ts
  tests/integration/db-explorer/db-explorer.spec.ts
  tests/integration/desktop-only/desktop-only.spec.ts
  tests/integration/error-fallback.spec.ts
  tests/integration/file-explorer/file-explorer.spec.ts
  tests/integration/file-import-export/add-files.spec.ts
  tests/integration/fixtures/base.ts
  tests/integration/fixtures/page.ts
  tests/integration/fixtures/test-tmp.ts
  tests/integration/onboarding/onboarding.spec.ts
  tests/integration/start-guide/start-guide.spec.ts
  tests/integration/utils.ts
  tests/integration/webkit/404.spec.ts
  tests/integration/webkit/onboarding.spec.ts
  tests/integration/whats-new-modal/utils.ts
  tests/integration/whats-new-modal/whats-new-modal.spec.ts
Labels: infra, skip-changelog

#121 [Feature]: Enabled file drag and drop
  index.html
  src/components/dnd-overlay/dnd-overlay.tsx
  src/components/dnd-overlay/index.ts
  src/components/layout/layout.tsx
  src/hooks/use-add-local-files-folders.tsx
  tests/integration/file-explorer/drag-drop.spec.ts
Labels: enhancement, ux
