Repository pondpilot/pondpilot, pull requests merged in 2025-06, with the labels that each got.

#131 [Feature, Bug]: Make app database persistent, add httpfs support, allow ATTACH and fix CTE display
  package.json
  src/app.tsx
  src/components/database-management/database-management-settings.tsx
  src/components/database-management/index.ts
  src/components/multiple-tabs-blocked/index.ts
  src/components/multiple-tabs-blocked/multiple-tabs-blocked.tsx
  src/controllers/db-persistence/db-persistence-controller.ts
  src/controllers/db-persistence/index.ts
  src/features/app-context/app-context.tsx
  src/features/duckdb-context/duckdb-connection-pool.ts
  src/features/duckdb-context/duckdb-context.tsx
  src/features/duckdb-context/duckdb-pooled-connection.ts
  src/features/duckdb-context/duckdb-pooled-prepared-stmt.ts
  src/features/duckdb-persistence-context/duckdb-persistence-context.tsx
  src/features/duckdb-persistence-context/index.ts
  src/features/feature-context/feature-context.tsx
  src/features/feature-context/index.ts
  src/features/init-modals/init-modals.tsx
  src/hooks/use-tab-coordination.ts
  src/models/db-persistence.ts
  src/pages/settings-page/settings-page.tsx
  src/router/router.tsx
  src/utils/duckdb-persistence.ts
  src/utils/editor/sql.ts
  src/utils/opfs.ts
  tests/integration/file-explorer/file-explorer.spec.ts
  yarn.lock
Labels: bug, enhancement, deps

#162 [Bug]: Use correct name of internal database operations across controllers and features
  src/controllers/data-source/data-view-source.ts
  src/controllers/db-explorer.ts
  src/controllers/db-persistence/db-persistence-controller.ts
  src/controllers/db/duckdb-meta.ts
  src/controllers/file-explorer.ts
  src/controllers/file-system/file-system-controller.ts
  src/features/editor/ai-assistant-tooltip.ts
  src/features/editor/auto-complete.tsx
  src/features/tab-view/components/script-tab-view.tsx
  src/models/ai-service.ts
  src/models/db-persistence.ts
  src/store/app-store.tsx
  src/utils/ai-config.ts
  src/utils/ai-service.ts
  src/utils/schema-context-service.ts
Labels: bug, skip-changelog

#126 [Feature]: Add TSV, MD, SQL, Excel & XML export formats
  .eslintrc.cjs
  eslint-custom-rules/no-playwright-page-methods.js
  eslint-local-rules/index.js
  package.json
  src/components/export-options-modal/components/csv-options.tsx
  src/components/export-options-modal/components/format-selector.tsx
  src/components/export-options-modal/components/index.ts
  src/components/export-options-modal/components/markdown-options.tsx
  src/components/export-options-modal/components/sql-options.tsx
  src/components/export-options-modal/components/tsv-options.tsx
  src/components/export-options-modal/components/xlsx-options.tsx
  src/components/export-options-modal/components/xml-options.tsx
  src/components/export-options-modal/constants.ts
  src/components/export-options-modal/export-options-modal.tsx
  src/components/export-options-modal/index.ts
  src/components/export-options-modal/validation.ts
  src/features/tab-view/components/data-view-info-pane/data-view-info-pane.tsx
  src/features/tab-view/hooks/index.ts
  src/features/tab-view/hooks/use-table-export.tsx
  src/models/export-options.ts
  src/utils/export-data.ts
  src/utils/tab-utils.ts
  tests/integration/data-viewer/export.spec.ts
  tests/integration/desktop-only/desktop-only.spec.ts
  tests/integration/error-fallback.spec.ts
  tests/integration/fixtures/data-view.ts
  tests/integration/fixtures/page.ts
  tests/integration/onboarding/onboarding.spec.ts
  tests/integration/webkit/404.spec.ts
  tests/integration/webkit/onboarding.spec.ts
  tests/integration/whats-new-modal/whats-new-modal.spec.ts
  tests/unit/utils/export-data.test.ts
  yarn.lock
Labels: enhancement

#164 [Fix, Feature]: Clean-up error context if AI fix was applied
  src/components/creatable-select/creatable-select.tsx
  src/components/creatable-select/index.ts
  src/features/editor/ai-assistant-tooltip.ts
  src/features/editor/ai-assistant/effects.ts
  src/features/editor/ai-assistant/structured-response-handlers.ts
  src/pages/settings-page/components/ai-settings/ai-settings.tsx
  src/utils/ai-config.ts
  src/utils/ai-service.ts
Labels: bug

#168 [UX]: Fix whats new modal lists style, normalize github links to make it clickable
  .github/release-drafter.yml
  CHANGELOG.md
  src/features/whats-new-modal/whats-new-modal.tsx
Labels: bug, ux, skip-changelog

#166 Add @-mentions for datasets and queries and prompt history
  src/components/global-navigation-handler/global-navigation-handler.tsx
  src/components/global-navigation-handler/index.ts
  src/components/layout/layout.tsx
  src/features/editor/ai-assistant-tooltip.ts
  src/features/editor/ai-assistant/ai-assistant-handlers.ts
  src/features/editor/ai-assistant/constants.ts
  src/features/editor/ai-assistant/effects.ts
  src/features/editor/ai-assistant/error-handler.ts
  src/features/editor/ai-assistant/managers/history-manager.ts
  src/features/editor/ai-assistant/managers/mention-manager.ts
  src/features/editor/ai-assistant/mention-autocomplete.ts
  src/features/editor/ai-assistant/model.ts
  src/features/editor/ai-assistant/prompt-history.ts
  src/features/editor/ai-assistant/services-facet.ts
  src/features/editor/ai-assistant/state-field.ts
  src/features/editor/ai-assistant/structured-response-builders.ts
  src/features/editor/ai-assistant/structured-response-handlers.ts
  src/features/editor/ai-assistant/structured-response-widget.ts
  src/features/editor/ai-assistant/themes/ai-widget-base.ts
  src/features/editor/ai-assistant/themes/ai-widget-input.ts
  src/features/editor/ai-assistant/themes/index.ts
  src/features/editor/ai-assistant/themes/mention-dropdown.ts
  src/features/editor/ai-assistant/themes/structured-response.ts
  src/features/editor/ai-assistant/ui-factories.ts
  src/features/editor/ai-assistant/utils/cleanup-registry.ts
  src/features/editor/ai-assistant/utils/dropdown-styles.ts
  src/features/editor/ai-assistant/utils/mention-categorization.ts
  src/features/editor/ai-assistant/utils/sanitization.ts
  src/features/editor/ai-assistant/widget-builders.ts
  src/features/editor/sql-editor.tsx
  src/features/script-editor/script-editor.tsx
  src/hooks/use-global-navigation.ts
  src/models/ai-service.ts
  src/router/router.tsx
  src/utils/ai-service.ts
  src/utils/route-navigation.ts
  src/utils/schema-context-service.ts
  tests/integration/ai-assistant/ai-assistant-error-context.spec.ts
  tests/integration/ai-assistant/ai-assistant-structured-response.spec.ts
  tests/integration/ai-assistant/ai-assistant.spec.ts
  tests/unit/ai-assistant/fuzzy-score.test.ts
  tests/unit/ai-assistant/mention-categorization.test.ts
  tests/unit/ai-assistant/mention-extraction.test.ts
Labels: enhancement

#179 Enable autocomplete with tab
  src/features/editor/sql-editor.tsx
Labels: enhancement
